### ISSUE TITLE
Cannot Install Conda Environment

### ISSUE THREAD

**Issue by TreezzZ** [pcyin/zeroshot_parser#1]
Thanks for your work!

In `zeroshot_parser/data/env.yml`, it seems we need to install `my_fairseq` according to `git+https://github.com/pcyin/my_fairseq.git@b5d99fd43b807f3194820ec12bfca4a368e44bf4`. 

In `my_fairseq/.gitmodules`, it shows you use `https://github.com/myleott/transformers.git`. However, this repo has removed. Do we have another repo that can replace it?

**Comment by pcyin** [comment]
Hey @TreezzZ, apologies for the super late reply! I wasn't on github for a while.

My codebase doesn't require this gitmodule. If you can figure out a way to install fairseq without `myleott/transformers.git` that'd be great. Otherwise please ping me.
